apiVersion: v2
name: outline
description: The outline helm chart to deploy outline in kubernetes clusters.
version: 0.1.0
appVersion: 0.75.2
home: https://encircle360.com
sources:
  - https://gitlab.com/encircle360-oss/helm-charts/outline
  - https://github.com/encircle360-oss/outline-helm-chart
keywords:
  - outline
  - wiki
  - helm
  - chart
  - kubernetes
  - s3
  - minio
  - postgresql
  - mongodb
  - knowledge
maintainers:
  - name: encircle360 GmbH
    email: hello@encircle360.com
    url: https://encircle360.com
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 15.2.5
    condition: postgresql.enabled
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 19.1.3
    condition: redis.enabled
  - name: minio
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.3.0
    condition: minio.enabled
