apiVersion: v1
name: outline
description: The outline helm chart to deploy outline in kubernetes clusters.
version: 0.0.5
appVersion: 0.61.1
home: https://encircle360.com
sources:
  - https://gitlab.com/encircle360-oss/helm-charts/outline
  - https://github.com/encircle360-oss/outline-helm-chart
keywords:
  - outline
  - wiki
  - helm
  - chart
  - kubernetes
  - s3
  - minio
  - postgresql
  - mongodb
  - knowledge
maintainers:
  - name: encircle360 GmbH
    email: hello@encircle360.com
    url: https://encircle360.com
  - name: Sascha Wolff
    email: sw@saschawolff.de
    url: https://saschawolff.de