apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "outline.fullname" . }}-migrate
  labels:
    {{- include "outline.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: {{ include "outline.fullname" . }}-migrate
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "outline.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "outline.env" . | nindent 12 }}
          args:
            - "yarn"
            - "db:migrate"
            - "--env=production-ssl-disabled"