dependencies:
  - name: postgresql
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    version: 10.12.2
    alias: postgresql
    condition: postgresql.enabled
  - name: redis
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    version: 15.4.1
    alias: redis
    condition: redis.enabled
  - name: minio
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    version: 7.2.0
    alias: minio
    condition: minio.enabled
