name: Release the Chart

on:
  push:
    branches:
      - main

env:
  CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  CR_OWNER: "tiagoblackcode"
  CR_GIT_REPO: outline-helm-chart

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    container: quay.io/helmpack/chart-releaser
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      
      - name: Add helm repositories
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Package the Chart
        run: cr package .
      
      - name: Upload the Chart
        run: cr upload

      - name: Create the index directory
        run: mkdir -p .cr-index
      
      - name: Update the index
        run: cr index --push
